# These are supported funding model platforms

github: [AchimPieters] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: AchimPieters # Replace with a single Open Collective username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
